import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const isWatch = process.argv.includes("--watch");

const buildOptions = {
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        ...builtins,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: "inline",
    treeShaking: true,
    outfile: "main.js",
    minify: false,
};

if (isWatch) {
    const context = await esbuild.context(buildOptions);
    await context.watch();
    console.log("👀 Watch 模式已启动，文件变化将自动重新编译...");
    // watch 模式下保持进程不退出
    setInterval(() => {}, 1 << 30);
} else {
    await esbuild.build(buildOptions);
    console.log("✅ 编译完成，main.js 已更新");
}
